### ISSUE TITLE
Invalid code generated: initialization discards ‘const’ qualifier from pointer target type

### ISSUE THREAD

**Issue by cblp** [GaloisInc/ivory#101]
Source:
```haskell
test :: Def ('[ConstRef s ('Stored (Ptr 'Global ('Stored Uint8)))] ':-> ())
test = proc "test" $ \refptr -> body $ do
      ptr <- deref refptr
      withRef
        ptr
        (\ref -> do
           val <- deref ref
           store ref (val + 1))
        (pure ())
```

Generated:
```c
void test(const uint8_t **n_var0) {
    uint8_t *n_deref0 = *n_var0;
    if ((bool) (NULL != n_deref0)) {
        uint8_t n_deref1 = *n_deref0;       
        *n_deref0 = (uint8_t) (n_deref1 + (uint8_t) 1U);
    }
}
```

GCC error:
```
test.c: In function ‘test’:
test.c:8:25: error: initialization discards ‘const’ qualifier from pointer target type [-Werror=discarded-qualifiers]
     uint8_t *n_deref0 = *n_var0;
                         ^
```

Reason: `const a * *` (mutable pointer to mutable pointer to constant data) is wrong C encoding of type `ConstRef _ ('Stored (Ptr _ ('Stored a)))`, right encoding is `a * const *` (mutable pointer to constant pointer to mutable data).

**Comment by cblp** [comment]
Moreover, it seems wrong to have distinct ConstRef/ConstPtr types. Constancy must be an attribute of pointed type. The Haskell encoding of pointer-to-constant type should be kind of `Ref s (Stored (Const a))`. And `Const a :: *` should be just a data type.

The same for `volatile`.

**Comment by cblp** [comment]
Looks like we should blame https://github.com/mainland/language-c-quote/issues/73

**Comment by leepike** [comment]
Ok, I believe this is merged and resolved, correct?

**Comment by cblp** [comment]
yes, #102 fixes this

**Comment by cblp** [comment]
Is release scheduled?

**Comment by leepike** [comment]
You mean a new Hackage release? We could do that.

**Comment by cblp** [comment]
Yes, please. We use Hackage as a centre of authority for all our dependencies.

**Comment by leepike** [comment]
Ok, everything is bumped in Hackage.

**Comment by cblp** [comment]
Thanks!
