### ISSUE TITLE
Hackage build failed

### ISSUE THREAD

**Issue by cblp** [GaloisInc/ivory#103]
http://hackage.haskell.org/package/ivory-0.1.0.5/reports/3

**Comment by leepike** [comment]
Sigh. Ok. I won't be able to push a fix until tonight, likely.

**Comment by leepike** [comment]
Ok, I edited Hackage directly for `ivory`, `ivory-examples`, and `ivory-backend-c`. It appears to build on my machine in a fresh sandbox on GHC 8.0.1 now, but let's wait to see what Hackage says.

**Comment by leepike** [comment]
Huh, Hackage still hasn't tried to rebuild the package. It also works on Travis-CI, though.

**Comment by leepike** [comment]
[Fixed!](http://hackage.haskell.org/package/ivory-0.1.0.6)
