### ISSUE TITLE
The documentation for the latest version of this package is missing on Hackage. 

### ISSUE THREAD

**Issue by expipiplus1** [GaloisInc/ivory#106]
The documentation for the latest version of this package is missing on Hackage. It's possible that Hackage wasn't able to build the package. see #103

Is it possible for you to manually upload the package using `cabal upload --doc`, please? Note that this requires cabal-install >= 1.24

Thanks!

**Comment by leepike** [comment]
[Fixed!](http://hackage.haskell.org/package/ivory-0.1.0.6)

**Comment by expipiplus1** [comment]
Thanks!
