### ISSUE TITLE
Add support for template-haskell-2.12

### ISSUE THREAD

**Issue by glguy** [GaloisInc/ivory#110]
GHC 8.2 and template-haskell-2.12 changed some of the types of definitions used by ivory.

Instead of patching in some CPP to handle these changes, it would be good to depend on [th-abstraction](https://hackage.haskell.org/package/th-abstraction) to paper over the changes.

**Comment by wiz** [comment]
GHC 8.4 is out, bringing `template-haskell-2.13`.
