### ISSUE TITLE
Remember constness in AST for deref statements

### ISSUE THREAD

**Issue by jameysharp** [GaloisInc/ivory#24]
The generated AST for `deref` statements discards information about whether the reference on the right-hand side was const or not.

That isn't wrong, since `deref` is safe for both const and non-const refs.

But it means that CSE can't insert temporary variables for subexpressions that keep constness identical to the original types.

Which again, isn't wrong. As long as CSE assumes all subexpressions on the RHS of a dereference *are* const, any temporary assignments can only *add* const to a pointer, not remove it. So this respects C semantics and remains safe.

But if a non-const ref is used in both a dereference (treated as const) and a store (treated as non-const), then this strategy means CSE will emit two sets of temporary variables for the same subexpression used at two types which differ only in constness.

That's annoying, as it makes the generated code bigger, but otherwise harmless. Still, it would be nice to fix someday.

Lee suggests this is part of a larger refactoring to do someday, where more type information should be carried around in the AST, saying the current approach is "not such a good idea for issues like this, and even just that in AST traversals, the reference type must be reconstructed." But we agree that fixing that is a big change for the amount of benefit it would provide.

**Comment by leepike** [comment]
I'm closing this. The CSE has been a huge win (thanks, @jameysharp!), and as Jamey mentions, it'd be a pretty big refactoring (even bigger now than when the issue was opened) for a modest gain.
