### ISSUE TITLE
Hackage version is incompatible with GHC 7.8.4

### ISSUE THREAD

**Issue by nponeccop** [GaloisInc/ivory#25]
It's still with older `GHC.TypeLits`, `base < 4.7` etc, so it isn't useful with `ghc-7.8.4`.

I'm packaging interesting Hackage packages for ArchLinux, and not having Hackage packages is a real obstacle. The build procedure still uses `cabal sandbox`, so I don't see a reason why fresh Ivory cannot be on Hackage.

**Comment by leepike** [comment]
Yes. We need to make a new release. We have a couple of issues we'd like to fix before making a new release, and I'm hoping we can have the next release done by the end of Feb. Does that work?

**Comment by nponeccop** [comment]
Sure. As long as you aware of the issue

**Comment by schell** [comment]
I started an ivory project today and ran into this as well, though I'm on 7.8.3 :)

**Comment by leepike** [comment]
Ok, thanks. A hackage release is imminent; please build from Github sources until then.

**Comment by schell** [comment]
All good and thank you! :+1:

**Comment by elliottt** [comment]
I just got the master branch working with 7.6.3, 7.8.4 and 7.10.3, should we do a release so that we can close this ticket?

**Comment by pierrebeaucamp** [comment]
Any update on this? I would love to have a working release on Hackage again.

**Comment by leepike** [comment]
Sorry for the delay. We'll push a release this week.

**Comment by leepike** [comment]
After a shameful >1 yr delay, I have uploaded new packages to Hackage. Let me know if you have any problems. I'll close the ticket, but reopen it if there are issues. Thanks for your patience.

**Comment by nponeccop** [comment]
Works for me in 7.10.3. Congratulations!

**Comment by pierrebeaucamp** [comment]
Same here, thank you.
