### ISSUE TITLE
Extern.hs example fails sanity-check (Unbound value)

### ISSUE THREAD

**Issue by Hodapp87** [GaloisInc/ivory#29]
ivory-examples/examples/Extern.hs appears to be broken; 'runExtern' produces the following error:
```
*** Procedure Extern
    ERROR: [ No location available ]:
             Unbound value: 'putchar'
    ERROR: [ No location available ]:
             Unbound value: 'SOME_CONST'
    ERROR: [ No location available ]:
             Unbound value: 'putchar'
*** Exception: Sanity-check failed!
```
I noticed this when all of my external functions using `externProc` were causing that "Unbound value" error - but I could remedy this by instead using `importProc` with the appropriate header, and then using `incl` in the module.

However, this is the offending code for `SOME_CONST`:

```haskell
x :: Uint8
x = extern "SOME_CONST"
```
and I don't know any equivalent fix for `extern` or any other way to reference an external constant.

**Comment by leepike** [comment]
We turned on "sanity-checking" by default to check that items are defined and of the right type. Yes, use `importProc` and `incl` to include them. I believe you are right about `extern` constants. For now, set `scErrors = False` in the compiler options, and I'll reply here with a fix.

**Comment by expipiplus1** [comment]
Is there some way to disable sanity checking for particular definitions. It's a shame to have to disable this for a whole module just to use some external constant.

**Comment by leepike** [comment]
Sorry for leaving this issue open so long. I've pushed a commit that should fix these issues (https://github.com/GaloisInc/ivory/tree/fix-externs). I need to see if it (1) passes continuous integration and (2) run the API changes by our other known Ivory users and developers before I push to Master.

The commit https://github.com/GaloisInc/ivory/commit/b0f41b57c4af3bed207cb17b2920d88947a14ef3 outlines the API changes.

**Comment by leepike** [comment]
The commit referenced above has been merged into Master. Please report any issues or errors.
