### ISSUE TITLE
backend should warn if you're emitting modules or artifacts with the same filename

### ISSUE THREAD

**Issue by pchickey** [GaloisInc/ivory#32]
Currently there's no warning that the user (accidentally) created modules or artifacts of the same name - whichever one gets written to disk last (which is arbitrary) "wins". This doesn't come up a lot in practice but when it does, it sure can be difficult to debug!

**Comment by jameysharp** [comment]
I think it might reasonably happen that the same artifact (or possibly even the same module) is included twice. I think it would be nice to detect that the duplicates have the same contents and not warn in that case.

**Comment by leepike** [comment]
Should be fixed as of commit 8e891eb9047b4b. If you're generating a lot of duplicate files, things might be a little slow (I'm doing comparison on (byte)strings), but overwriting files should be a rare occurrence.

**Comment by pchickey** [comment]
Thanks Lee!

**Comment by pchickey** [comment]
had to revert these changes - they were incorrect and resulted the code generator failing nondeterministicly. https://github.com/GaloisInc/ivory/commit/4d6a5ebce563db7f5b030bbac7d316d96428448c

**Comment by pchickey** [comment]
i fixed this a little while ago
