### ISSUE TITLE
Rename `forever`

### ISSUE THREAD

**Issue by elliottt** [GaloisInc/ivory#4]
The `forever` loop combinator clashes in name with the perfectly useful function of the same name from `Control.Monad`.  It would be nice to rename our `forever` to something else, so that the clash doesn't exist.

**Comment by pchickey** [comment]
Closing - we haven't had anyone complain about this in everyday use. I agree in principle, but its so far been very rare that anyone is using both Control.Monad and Ivory.Language at once.
