### ISSUE TITLE
Build fails on GHC 7.10.1 (can't install HStringTemplate-0.7.3)

### ISSUE THREAD

**Issue by Hodapp87** [GaloisInc/ivory#40]
I observed this on my ArchLinux box that I had just updated. I just reproduced it on a fresh Ubuntu VM using binary GHC 7.10.1 from https://www.haskell.org/ghc/dist/7.10.1/ghc-7.10.1-x86_64-unknown-linux-deb7.tar.bz2 and Cabal from https://www.haskell.org/cabal/release/cabal-install-1.22.2.0/cabal-install-1.22.2.0.tar.gz with 'cabal update' run right beforehand.

Running 'make' gives the following output:
```
cabal sandbox init
Writing a default package environment file to
/home/hodapp/ivory/cabal.sandbox.config
Creating a new sandbox at /home/hodapp/ivory/.cabal-sandbox
echo "tests: True" >> cabal.sandbox.config
cabal sandbox add-source  ivory/  ivory-artifact/  ivory-backend-acl2/  ivory-backend-c/  ivory-eval/  i
vory-examples/  ivory-hw/  ivory-model-check/  ivory-opts/  ivory-quickcheck/  ivory-serialize/  ivory-s
tdlib/
cabal install  ivory/  ivory-artifact/  ivory-backend-acl2/  ivory-backend-c/  ivory-eval/  ivory-exampl
es/  ivory-hw/  ivory-model-check/  ivory-opts/  ivory-quickcheck/  ivory-serialize/  ivory-stdlib/
Resolving dependencies...
cabal: Could not resolve dependencies:
trying: ivory-0.1.0.2 (user goal)
trying: hpc-0.6.0.2/installed-ac9... (dependency of ivory-0.1.0.2)
trying: ivory-artifact-0.1.0.0 (user goal)
next goal: HStringTemplate (dependency of ivory-artifact-0.1.0.0)
rejecting: HStringTemplate-0.8.3, 0.8.2, 0.8.1, 0.8 (conflict: ivory-artifact
=> HStringTemplate==0.7.3)
rejecting: HStringTemplate-0.7.3 (conflict: hpc =>
time==1.5.0.1/installed-e17..., HStringTemplate => time<1.5)
rejecting: HStringTemplate-0.7.1, 0.7.0, 0.6.12, 0.6.11, 0.6.10, 0.6.9, 0.6.8,
0.6.6, 0.6.5, 0.6.4, 0.6.3, 0.6.2, 0.6.1, 0.6, 0.5.1.3, 0.5.1.2, 0.5.1.1,
0.5.1, 0.5, 0.4.3, 0.4.2, 0.4.1, 0.4, 0.3.2, 0.3.1, 0.3, 0.2 (conflict:
ivory-artifact => HStringTemplate==0.7.3)
Dependency tree exhaustively searched.

Note: when using a sandbox, all packages are required to have consistent
dependencies. Try reinstalling/unregistering the offending packages or
recreating the sandbox.
make: *** [build] Error 1
```

**Comment by pchickey** [comment]
Hi Chris, thanks for reporting this. I pinned ivory-artifact to that specific HStringTemplate version a little while ago due to issues with newer versions building under GHC 7.8.

I've unpinned it in a branch to see whether the Travis build works out under 7.8: https://travis-ci.org/GaloisInc/ivory/builds/57649565 . If it does, I'll push that to master.

We aren't yet officially supporting GHC 7.10 - unfortunately, we don't have spare cycles to spend on this in the next few weeks. It is on our list to do in the near future - probably after our mid-may milestone. However, we're very happy for you to keep reporting bugs on it.

**Comment by Hodapp87** [comment]
Thanks @pchickey - I'll check in a bit. Luckily, I don't need GHC 7.10 support, and just ran into this by accident.

**Comment by pchickey** [comment]
unpinned HStringTemplate built fine in Travis, so I've merged it into master @ f431171f

**Comment by Hodapp87** [comment]
I'm building with https://gist.github.com/Hodapp87/ae6b61c75001c68f90c8 right now. Most of it looks like foldable-traversal stuff from GHC 7.10. I've disabled `ivory-examples` because `wl-pprint` depends on old base.

I'll do a pull request if I make any progress there that doesn't involve disabling parts of the build.

**Comment by pchickey** [comment]
Looks like `wl-pprint` isn't used by ivory-examples- it must have been left over from a long time ago. I've removed it in 944271

**Comment by elliottt** [comment]
Master builds with ghc-7.10.3 now. I'm happy to re-open the ticket if you're still running into build problems :)
