### ISSUE TITLE
Floating point casts aren't value-preserving

### ISSUE THREAD

**Issue by jameysharp** [GaloisInc/ivory#42]
We currently have `SafeCast` instances for `Sint32 -> IFloat` and `Sint64 -> IDouble`, but these casts don't preserve the value of the original expression for all inputs, because the input has more bits of precision than the mantissa of the output.

I think we should add a `FloatCast` class, which allows casts that lose precision while preserving approximate magnitude. That should have `Sint32 -> IFloat`, `Sint64 -> IFloat`, and `Sint64 -> IDouble` casts. Casts from smaller integer types can stay in the `SafeCast` class.

**Comment by leepike** [comment]
Looks good to me. Likewise, we should add the new operator to the concrete syntax.

**Comment by leepike** [comment]
Well, I'm not sure what to do about this now. I think many users have safe `safeCast`s that aren't value preserving, so this wouldn't be a backwards compatible change.

Perhaps I can add the `FloatCast` and mark those instances of `safeCast` as deprecated?

**Comment by leepike** [comment]
I'm closing this, given that it's not backwards compatible. We just need to be sure that it's clear that the semantics of `safeCast` aren't necessarily value-preserving.

**Comment by AleXoundOS** [comment]
I think it should be noted in the documentation.
