### ISSUE TITLE
Sanity-check variable/typedef collisions

### ISSUE THREAD

**Issue by leepike** [GaloisInc/ivory#44]
The backend is changed (commit 02ef9f5e8345ae06a183) to declare structs with the form

    typedef struct foo { ... } foo;

for compatibility issues with a particular target.

It might be nice to add a sanity check to ensure the same symbol isn't used for a struct typedef and a global variable, eventually resulting in a C compilation error.

**Comment by pchickey** [comment]
lets relabel this as a bug, since the sanity checker could have caught an error related to this that ended up getting caught by gcc

**Comment by pchickey** [comment]
(oops I hit the wrong button...)

**Comment by leepike** [comment]
Added in commit 047cab6. These are warnings if `sanity-check`ing is enabled. They are not errors---indeed, our own Ivory regression tests violates this, since we create a number of modules with the same symbols, compile them, but do not link them.
