### ISSUE TITLE
ivory-backend-c: constness of ref to array of array is wrong

### ISSUE THREAD

**Issue by pchickey** [GaloisInc/ivory#45]
see build failure here. will work on a smaller test case when i have some spare time
https://travis-ci.org/GaloisInc/smaccmpilot-stm32f4/jobs/66928694

**Comment by leepike** [comment]
Hmm... The there may be a more general issue with matrices. The following code

```haskell
foo :: Def ('[Ref s ('Array 1 ('Array 2 ('Stored Uint32)))] ':-> Uint32)
foo = proc "foo" $ \arr -> body $ do
  v <- deref (arr ! 1 ! 0)
  ret v

bar :: Def ('[] ':-> Uint32)
bar = proc "bar" $ body $ do
  arr <- local (iarray [iarray [ival 0, ival 1]])
  v <- call foo arr
  ret v
```
produces incorrect C:

```c
uint32_t foo(uint32_t n_var0[1U][2U])
{
    uint32_t n_deref0 = n_var0[(int32_t) 1 % 1][(int32_t) 0 % 2];

    return n_deref0;
}
uint32_t bar(void)
{
    uint32_t n_local0[1U][2U] = {{(uint32_t) 0U, (uint32_t) 1U}};
    uint32_t n_ref1[2U] = n_local0;
    uint32_t n_r2 = foo(n_ref1);

    return n_r2;
}
```
Specifically, `uint32_t n_ref1[2U] = n_local0` is an invalid initialization.

**Comment by leepike** [comment]
I couldn't recreate @pchickey's bug, but I did find an array decay bug, reported above, that I fixed. I also cleaned up the code generator w.r.t. to array decays.

I'm closing this ticket, assuming (hoping) the original bug was fixed.
