### ISSUE TITLE
BitData constructor fields reversed

### ISSUE THREAD

**Issue by Hodapp87** [GaloisInc/ivory#51]
I am running the following: http://lpaste.net/1313446023258963968. The output with `-ddump-splices` is:
```haskell
[1 of 1] Compiling BitDataTest      ( BitDataTest.hs, interpreted )
BitDataTest.hs:1:1: Splicing declarations
    "\n\
    \ bitdata TestBd :: Bits 8 = bdConstr\n\
    \   { lower :: Bit\n\
    \   , upper :: Bits 7\n\
    \   }\n"
  ======>
    [newtype TestBd
       = TestBd (Bits 8)
       deriving (IvoryType,
                 IvoryVar,
                 IvoryExpr,
                 IvoryEq,
                 IvoryInit,
                 IvoryStore,
                 IvoryZeroVal),
     instance BitData TestBd where
       type Ivory.Language.BitData.BitData.BitType TestBd = Bits 8
       toBits (TestBd x) = x
       fromBits = TestBd,
     bdConstr :: Bit -> Bits 7 -> TestBd,
     bdConstr arg0 arg1
       = Ivory.Language.BitData.BitData.unsafeFromRep
           ((0 .| ((safeCast (toRep arg0)) `iShiftL` 0))
            .| ((safeCast (toRep arg1)) `iShiftL` 7)),
     upper :: BitDataField TestBd (Bits 7),
     upper = Ivory.Language.BitData.BitData.BitDataField 0 7 "upper",
     lower :: BitDataField TestBd Bit,
     lower = Ivory.Language.BitData.BitData.BitDataField 7 1 "lower"]
Ok, modules loaded: BitDataTest.
```
`bdConstr` looks correct to me - it just looks like `(lower << 0) | (upper << 7)`.

But, the `BitDataField` definition of `upper` then seems to be putting that field at the lower 7 bits, and the definition of `lower` seems to be putting it as the uppermost bit.

The output of `main` is:
```

// module bitdata_test Source:

#include "bitdata_test.h"
uint8_t bdTest(void)
{
    return (uint8_t) ((uint8_t) ((uint8_t) 0U |
                                 (uint8_t) ((uint8_t) (true ? (uint8_t) 1U : (uint8_t) ((uint8_t) 0U &
                                                                                        (uint8_t) 1U)) <<
                                            (uint8_t) 0U)) |
                      (uint8_t) ((uint8_t) ((uint8_t) 0U & (uint8_t) 127U) <<
                                 (uint8_t) 7U));
}
uint8_t bdTest2(void)
{
    return (uint8_t) ((uint8_t) ((uint8_t) 0U & (uint8_t) 255U) |
                      (uint8_t) ((uint8_t) 1U << (uint8_t) 7U));
}

// module bitdata_test Header:

#include "ivory.h"
uint8_t bdTest(void);
uint8_t bdTest2(void);
```
`bdTest` calls the constructor `bdConstr` with lower=1 and upper=0, and it looks correct there - I see 1 << 0.
`bdTest2` uses `withBits (0 :: Uint8) $ setBit lower` to create the value, and I see 1 << 7. Somehow the fields `lower` and `upper` have reversed in order.

**Comment by pchickey** [comment]
Good job uncovering this bug - because we only use bitdata to inspect and modify `Ivory.HW` `Reg`s I don't think we ever used the constructor functionality.

It seems that the constructor is incorrect. Our convention is that BitData fields declare the most significant bits first, so in this case, your naming of `lower` and `upper` in the quasiquoter are backwards according to that convention.

**Comment by pchickey** [comment]
We'll see if we can find some time to fix this soon (unfortunately we're all very booked rn with a deadline in 4 weeks) or you're welcome to give it a try yourself :)

**Comment by jameysharp** [comment]
Out of curiosity, do you really want the constructor syntax, or could we just delete the constructors entirely? I like naming each field using the monad syntax, for clarity and future maintenance.

**Comment by Hodapp87** [comment]
I'm not using the constructor. If it's not used anyplace internally, then there's probably no sense in devoting time to it now. I'll just refrain from using the constructor.

**Comment by Hodapp87** [comment]
@jameysharp, I don't really want it. I was just inspecting the splices, as I've been bypassing the quasiquoter for some things I'm doing and wanted to check that I was still doing things correctly, and seeing this inconsistency threw me for a loop. I use the monad syntax too.

**Comment by leepike** [comment]
I'm guessing this cropped up when I integrated James' original Parsec parser to Happy. I'll look into it Real Soon.

**Comment by leepike** [comment]
Ok, I think I found the culprit and fixed it in https://github.com/GaloisInc/ivory/commit/1837d947a25bce69128e4e1a47d9323cedd45cf3. It looks like a `foldr` was used in one place and a `foldl` in another. We still respect the most significant bit first convention.

**Comment by jameysharp** [comment]
Given that nobody could have used the constructors correctly, are you sure you don't want to just delete them?

**Comment by leepike** [comment]
Good point. In a perfect world, we'd clean up the qq syntax to not have a constructor symbol, too, but that'd break code.

**Comment by leepike** [comment]
Actually, I think those constructors were correct for sum bit-types, and could have been used (indeed, they're pretty natural there, as constants). Given that, I'm inclined to just leave them in.

**Comment by leepike** [comment]
I'm closing this w.r.t. the bug; let's open a new ticket about deprecating the constructors.
