### ISSUE TITLE
Newbie question: How to use importProc avoiding "ERROR: [ No location available ]:".

### ISSUE THREAD

**Issue by master-q** [GaloisInc/ivory#60]
I write following code:

https://github.com/fpiot/arduino-ivory/blob/531329db24cc67f423c211d0fdfa1b52ee6eb000/demo/01_blink/MainIvory.hsb

And I believe it create following C code:

```c
int main () {
    init();
    delay(500);
    return 0;
}
```

How ever it causes following error:

```
$ runhaskell MainIvory.hs

*** Procedure MainIvory
    ERROR: [ No location available ]:
             Unbound value: 'init'
    ERROR: [ No location available ]:
             Unbound value: 'delay'
MainIvory.hs: Sanity-check failed!
```

How to fix it?

**Comment by Hodapp87** [comment]
I'm getting a 404 on that URL. Did https://github.com/fpiot/arduino-ivory/commit/531329db24cc67f423c211d0fdfa1b52ee6eb000 fix it or is this still an issue?

**Comment by master-q** [comment]
Sorry. The issue is not yet fixed.

The code is following:

https://github.com/fpiot/arduino-ivory/blob/531329db24cc67f423c211d0fdfa1b52ee6eb000/demo/01_blink/MainIvory.hs

```haskell
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE TypeOperators #-}

import Ivory.Language
import qualified Ivory.Compile.C.CmdlineFrontend as C (compile)

arduino_header :: String
arduino_header = "Arduino.h"

c_init :: Def ('[] :-> ())
c_init = importProc "init" arduino_header

c_delay :: Def ('[Uint32] :-> ())
c_delay = importProc "delay" arduino_header

ivory_main :: Def ('[] :-> Sint16)
ivory_main = proc "main" $ body $ do
  call_ c_init
  call_ c_delay 500
  ret 0

main_ivory_module :: Module
main_ivory_module = package "MainIvory" $ do
  incl ivory_main

main :: IO ()
main = C.compile [ main_ivory_module ] []
```

**Comment by Hodapp87** [comment]
I don't know how to properly *solve* the issue, but you can work around it by turning off sanity checks with ```scErrors = False``` in compiler options - something like:

```haskell
main :: IO ()
main = C.runCompiler [ main_ivory_module ] [] opts
   where opts = C.initialOpts { C.scErrors = False }
```

I had reported something similar in https://github.com/GaloisInc/ivory/issues/29 and Lee says he fixed it. Are you using the Hackage release of Ivory, or the latest git version?

**Comment by jameysharp** [comment]
I believe your `main_ivory_module` just needs two more `incl` declarations, for `c_init` and `c_delay`, right?

**Comment by master-q** [comment]
You are right! My mistake is thinking that imported function doesn't need to be included.
I applied following patch:

```diff
diff --git a/demo/01_blink/MainIvory.hs b/demo/01_blink/MainIvory.hs
index 0c26ff0..48072ea 100644
--- a/demo/01_blink/MainIvory.hs
+++ b/demo/01_blink/MainIvory.hs
@@ -21,6 +21,8 @@ ivory_main = proc "main" $ body $ do
 
 main_ivory_module :: Module
 main_ivory_module = package "MainIvory" $ do
+  incl c_init
+  incl c_delay
   incl ivory_main
 
 main :: IO ()
```

I got  following C code:

```c
#include "MainIvory.h"

int16_t main(void)
{
    init();
    delay((uint32_t) 500U);
    return (int16_t) 0;
}
```

Thanks a lot!
