### ISSUE TITLE
Failure to Compile on openSUSE Linux

### ISSUE THREAD

**Issue by martinvahi** [GaloisInc/ivory#61]
ts2@linux-0fiz:~/tmp/xx9/2015_12_22_Ivory_Programming_Language/uhuu/ivory$ cabal --version
    cabal-install version 1.16.0.2
    using version 1.16.0 of the Cabal library 
    ts2@linux-0fiz:~/tmp/xx9/2015_12_22_Ivory_Programming_Language/uhuu/ivory$ nice -n20 make
    cabal sandbox init
    cabal: unrecognised command: sandbox (try --help)
    Makefile:23: recipe for target 'cabal.sandbox.config' failed
    make: *** [cabal.sandbox.config] Error 1
    ts2@linux-0fiz:~/tmp/xx9/2015_12_22_Ivory_Programming_Language/uhuu/ivory$ uname -a
    Linux linux-0fiz 3.16.7-29-desktop #1 SMP PREEMPT Fri Oct 23 00:46:04 UTC 2015 (6be6a97) x86_64 x86_64 x86_64 GNU/Linux
    ts2@linux-0fiz:~/tmp/xx9/2015_12_22_Ivory_Programming_Language/uhuu/ivory$ date
    Tue Dec 22 23:40:21 EET 2015
    ts2@linux-0fiz:~/tmp/xx9/2015_12_22_Ivory_Programming_Language/uhuu/ivory$ ls
    CODE_OF_CONDUCT.md  ivory-backend-c     ivory-hw           ivory-quickcheck  Makefile
    ivory               ivory-eval          ivory-model-check  ivory-serialize   Makefile.sandbox
    ivory-artifact      ivory-examples      ivory-opts         ivory-stdlib      README.md
    ivory-backend-acl2  ivory-formal-model  ivory-paper        LICENSE
    ts2@linux-0fiz:~/tmp/xx9/2015_12_22_Ivory_Programming_Language/uhuu/ivory$ ghc -v
    Glasgow Haskell Compiler, Version 7.6.3, stage 2 booted by GHC version 7.6.3
    Using binary package database: /usr/lib64/ghc-7.6.3/package.conf.d/package.cache
    wired-in package ghc-prim mapped to ghc-prim-0.3.0.0-d5221a8c8a269b66ab9a07bdc23317dd
    wired-in package integer-gmp mapped to integer-gmp-0.5.0.0-2f15426f5b53fe4c6490832f9b20d8d7
    wired-in package base mapped to base-4.6.0.1-8aa5d403c45ea59dcd2c39f123e27d57
    wired-in package rts mapped to builtin_rts
    wired-in package template-haskell mapped to template-haskell-2.8.0.0-a3012803fde1dc362e555b35a1a78e6d
    wired-in package dph-seq not found.
    wired-in package dph-par not found.
    Hsc static flags: -static
    *** Deleting temp files:
    Deleting: 
    *** Deleting temp dirs:
    Deleting: 
    ghc: no input files
    Usage: For basic information, try the `--help' option.
    ts2@linux-0fiz:~/tmp/xx9/2015_12_22_Ivory_Programming_Language/uhuu/ivory$

**Comment by Hodapp87** [comment]
What it looks like to me: The build uses a Cabal sandbox, but your version of cabal-install is too old to support sandboxes. If your repos don't have a newer version, you may need to do something like ```cabal install cabal-install```, and add ```~/.cabal/bin``` to the beginning of your PATH variable.

**Comment by leepike** [comment]
This problem should be deprecated as we've now moved to a Stack-based build.
