### ISSUE TITLE
cvc4 modeling error in tutorial

### ISSUE THREAD

**Issue by dagit** [GaloisInc/ivory#69]
This example comes from the ivory-tutorial exercises. Attempting to model check potion usage.

```
[ivory|

struct Character
  { hp     :: Stored Uint16
  ; max_hp :: Stored Uint16
  ; mp     :: Stored Uint16
  ; max_mp :: Stored Uint16
  ; potions:: Stored Uint8
  }

void use_potion(*struct Character c) {
  let ps = *c.potions;

  if (ps > 0) {
    -- decrement the number of available potions
    store c.potions as (ps - 1);

    -- increase mp up to the maximum
    let mp_val = *c.mp;
    let mp_max = *c.max_mp;
    if ((mp_val + 25) < mp_max) {
      store c.mp as (mp_val + 25);
    } else {
      store c.mp as mp_max;
    }
  } else {}
}
|]

potions_available ref =
  checkStored (ref ~> potions) $ \ potions_val ->
    1 <=? potions_val

check_potion_use :: Def ('[Ref s ('Struct "Character")] ':-> ())
check_potion_use =
  proc "check_potion_use" $ \ ref ->
  requires (potions_available ref) $
  body $ do
    old_potions <- deref (ref ~> potions)
    call_ use_potion ref
    new_potions <- deref (ref ~> potions)
    assert (old_potions >? new_potions)
```

We're getting this error message with the 1.5 developer snapshot and the 1.4 release of cvc4:
```
Unsafe ["QUERY deref1 > mc_1deref2 ;\t % [ No location available ];"]
```

We also turned on Inlining for this example because `use_potion` needs to be inlined. 

@elliottt, @leepike thinks this may be related to the fresh name generation with inlining.

**Comment by dagit** [comment]
After some more debugging (using asserts in the concrete syntax, and no function call to inline) we still see the issue, but commenting out the inner most if-statement the model checker can find a proof.

**Comment by gridaphobe** [comment]
It's been a while since I looked at the model checker, but this line

https://github.com/GaloisInc/ivory/blob/eceb031a3b6a71bd7302ac6805a65037f80b1a22/ivory-model-check/src/Ivory/ModelCheck/Monad.hs#L351

looks suspicious to me. 

It should probably be `sets_ (\s -> s { symCond = b' &&. b })` to track nested if-statements, which is exactly the scenario here.

**Comment by dagit** [comment]
Thanks, you're probably right but I just tried it and I'm still getting unsafe. We'll dig deeper tomorrow.

Thanks!

**Comment by elliottt** [comment]
Ah, @leepike and I had talked about the nested if stuff, but we must have never made the change that @gridaphobe mentioned above.

**Comment by gridaphobe** [comment]
Actually, that's probably a separate bug. Digging in a bit more I noticed a few things

1. These two assertions correspond to the two branches of the inner if-statement, but the 2nd refers to the variable set by the first. That's totally bogus!
```
ASSERT ((deref2 + 25) < deref4) => (mc_2var0 = (mc_1var0 WITH .mp := deref2 + 25)) ;	 % [ No location available ];
ASSERT (NOT ((deref2 + 25) < deref4)) => (mc_3var0 = (mc_2var0 WITH .mp := deref4)) ;	 % [ No location available ];
```
If you rewrite the 2nd line to
```
ASSERT (NOT ((deref2 + 25) < deref4)) => (mc_3var0 = (mc_1var0 WITH .mp := deref4)) ;	 % [ No location available ];
```
the query is valid.

2. My copy of cvc 1.4 choked on `mc_1var0 WITH .mp := deref2 + 25`, it seemed to want extra parentheses around `deref2 + 25`.

**Comment by gridaphobe** [comment]
So this is a bug in the translation to cvc4. We need to restore the latest references when we return from `inBranch`.

**Comment by leepike** [comment]
Closing this, as we're rewriting the model checker (@eddywestbook).
