### ISSUE TITLE
[question] Automating creation of C-call redirect table

### ISSUE THREAD

**Issue by grwlf** [GaloisInc/ivory#70]
Hi. Lets say I have several procedures sharing same signature. I'd like Ivory to build a procedure which would act as a call gate - select  the right call branch by analyzing a selector variable. Here is the illustration:

```
syscalls_1 :: [ Def ('[Inp1] :-> Out1) ]
syscalls_1 = [
   proc "proc11" $ \a -> body ... ,
   proc "proc12" $ \a -> body ...
]

syscalls_2 :: [ Def ('[Inp2, Inp2] :-> Out2) ]
syscalls_2 = [
   proc "proc21" $ \a b -> body ... ,
   proc "proc22" $ \a b -> body ...
]

gate :: [(Int, Def (a :-> b))] -> Def ( (Uint32 ': a) :-> b)
gate pset = proc "gate" $ \ ??? (selector:args) ->
    ???  switch (selector) { 
              case 0 : call (pset !! 0) args ; break;
              case 1 : call (pset !! 1) args ; break ;
              ...
            }
    ???


```

Now I want to use `gate` to build a wrapper for all my syscalls. The resulting function should take additional argument describing an implementation to call :

```
syscall_1 :: Def ('[Uint32, Inp1] :-> Out1)
syscall_1= gate syscalls_1

syscall_2 :: Def ('[Uint32, Inp2, Inp2] :-> Out2)
syscall_2 = gate syscalls_2

```

Could you please help me to design the implementation of `gate` in Haskell ?
Thanks in advance.

**Comment by leepike** [comment]
Have you tried using `procPtr` in Ivory?

**Comment by leepike** [comment]
@grwlf let me know if this still an issue. Otherwise, as it's not really a bug or enhancement request for Ivory, I'm closing this for now. Please feel free to email me directly.
