### ISSUE TITLE
Using stored global refs 

### ISSUE THREAD

**Issue by leepike** [GaloisInc/ivory#77]
There has been a feature request by an Ivory user to allow areas (structs in particular) to contain global references that can be dereferenced. Of course, already you can have, e.g., 

```
[ivory|
struct Foo42
  { i42 :: Stored (Ref Global (Stored Uint32))
  }
|]
```

but you can't dereference or store the `Uint32` because of the `IvoryStore` constraint on `deref` and `store`.

What about adding an instance 

```
instance IvoryVar a => IvoryStore (Ref 'Global ('Stored a))
```

Is this safe?

**Comment by elliottt** [comment]
I don't think we can support this, as we can't ensure that the struct
wasn't initialized with zero.

**Comment by leepike** [comment]
Oh right, thanks. I keep forgetting initializers don't check subvalues. :/
