### ISSUE TITLE
Rename `ivoryCast` to `unsafeCast`

### ISSUE THREAD

**Issue by cblp** [GaloisInc/ivory#79]
It actually breaks all type safety.

**Comment by acfoltzer** [comment]
Agreed. The intent is not to have users import the module that exposes it, but enough reasons to import those modules have cropped up that we should be more careful with it.

**Comment by leepike** [comment]
Everything that is not explicitly exported in https://github.com/GaloisInc/ivory/blob/master/ivory/src/Ivory/Language.hs should be considered unsafe. By convention, we've tried to decorate any internal function that is unsafe with a

```
-- XXX Don't export.
```

Using any internals  means that all bets are off. It wouldn't make sense to rename each of these internal functions ```unsafeXXX```; there are at least a couple dozen of them.
