### ISSUE TITLE
Bug: String literals are treated as mutable `char *`

### ISSUE THREAD

**Issue by cblp** [GaloisInc/ivory#80]
When one writes string literal in Haskell it may go into Ivory as IString. Then IString compiles into string literal and its type to `char *`. So one can pass string literal to a C function taking `char *` and mutating its argument, which leads to segmentation fault.

Code to reproduce
```haskell
{-# LANGUAGE DataKinds         #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE TypeOperators     #-}

import qualified Ivory.Compile.C.CmdlineFrontend as C
import           Ivory.Language

nullifyString2 :: Def ('[IString] ':-> ())
nullifyString2 = importProc "nullifyString2" "nullifyString2.h"

nullifyString :: Def ('[IString] ':-> ())
nullifyString = proc "nullifyString" $ \s -> body $ do
    call_ nullifyString2 s

cmain :: Def ('[] ':-> Sint32)
cmain = proc "main" $ body $ do
    call_ nullifyString "hello"
    ret 0

ivoryStringIssue :: Module
ivoryStringIssue = package "gen-ivory-string-issue" $ do
    incl nullifyString2
    incl nullifyString
    incl cmain

main :: IO ()
main = C.compile [ivoryStringIssue] []
```

```c
// nullifyString2.h
void nullifyString2(char *s) {
    s[0] = 0;
}
```

I found this when tried to cast `puts :: Def ('[IString] ':-> Sint32)` to `int puts(const char *s)`.

**Comment by cblp** [comment]
Possible solutions:

1. If IString has mutable semantics, add IConstString with immutable semantics.
2. If IString has immutable semantics, translate it to `const char *`.
3. Document IString semantics.

**Comment by acfoltzer** [comment]
@elliottt do you have thoughts on this? I've not dealt much with `IString` yet, so I don't have a strong opinion

**Comment by elliottt** [comment]
I think it would be reasonable to change the code generator to produce a constant instead. Any objections?

**Comment by leepike** [comment]
I think I fixed this issue without touching the backend: I just changed the AST type for literal strings to be a constant reference to a char: https://github.com/GaloisInc/ivory/commit/1f725d23d8428599cae84a1f7f2523cc56c4104c

I'll merge to master.
