### ISSUE TITLE
Next hackage release?

### ISSUE THREAD

**Issue by wiz** [GaloisInc/ivory#87]
I wonder what's the current status of the code. Is it ready to use or there's still some showstoppers around?

Btw, please make it at least 0.1.1 as it contains breaking changes since 0.1.0.3 and CPP macro `MIN_VERSION_ivory` can only match first 3 components, preventing hassle-free dual version codebase.

**Comment by leepike** [comment]
Yes, it is ready to use. There are a few known bugs (see the other issues), but otherwise is well-tested.

We'll update the version soon.

**Comment by leepike** [comment]
Oops, forgot to mention here: Version 0.1.0.4 uploaded Oct. 29.
