### ISSUE TITLE
The documentation for the latest version of `ivory-backend-c` is missing on Hackage. 

### ISSUE THREAD

**Issue by expipiplus1** [GaloisInc/ivory#88]
The documentation for the latest version of `ivory-backend-c` is missing on Hackage. It's been pending on Hackage for some time, this usually indicated that Hackage wasn't able to build the package.

Is it possible for you to manually upload the package using `cabal upload --doc`, please?

Thanks!

**Comment by leepike** [comment]
I'll push new docs when we make a Hackage release soon.

**Comment by expipiplus1** [comment]
Thanks

**Comment by leepike** [comment]
I've made a new release for all the Ivory related packages at version 0.1.0.4 (ivory-quickcheck is 0.2.0.4, for no good reason). 

Ccing @cblp, @grwlf, @wiz, @Hodapp87, in case you're interested.

Sorry all for the delays in responding to issues!
