### ISSUE TITLE
Remove noop casts in the C code

### ISSUE THREAD

**Issue by leepike** [GaloisInc/ivory#91]
The casts in the C code prevents implicit casting (e.g., with arithmetic), as defined by the C standard, which is unintuitive. However, many of the casts are noops.

Remove noop casts in the C code generator.

**Comment by cblp** [comment]
Do you want to allow implicit casts happen? Why is it good?

**Comment by leepike** [comment]
No, I don't want to allow implicit casts. But implicit casts are part of the C standard, e.g., when doing arithmetic on types with sizes smaller than `int`.

That's why the generated C code explicitly casts on every operation. But it does so even when it is unnecessary. For example, currently, we can have code like the following, where `a`, `b`, and `c` are `uint8_t`s:

```c
uint8_t x = (uint8_t) (a + (uint8_t) (b + c))
```

But the extra typecasts are unnecessary in this context. They are, however, important for comparisons:

```c
bool x = a - b < 0
```

in which `a` and `b` are implicitly cast from `uint8_t` to a signed `int`. The comparison is done as an `int` type, in which case `a-b` can be negative, if there was overflow.

It's a trade-off trying to have a cleaner backend vs. possibly running into implicit cast surprises.

**Comment by cblp** [comment]
> a and b are implicitly cast from uint8_t to a signed int

> possibly running into implicit cast surprises

I find it a very complicated implicitness. I like very much how Ivory gives me strict typing in C programs, and I don't want to lose it.

**Comment by leepike** [comment]
You are probably right. This could be a lot of error-prone work in the C backend for not a lot of gain and potential bugs. I'll close this ticket.
